/*
 * action types
 */
export const GET_TODOS = 'GET_TODOS';
export const GET_TODOS_SUCCESSED = 'GET_TODOS_SUCCESSED';
export const GET_TODOS_FAILED = 'GET_TODOS_FAILED';

export const POST_TODO = 'POST_TODO';
export const POST_TODO_SUCCESSED = 'POST_TODO_SUCCESSED';
export const POST_TODO_FAILED = 'POST_TODO_FAILED';

export const PUT_TODO = 'PUT_TODO';
export const PUT_TODO_SUCCESSED = 'PUT_TODO_SUCCESSED';
export const PUT_TODO_FAILED = 'PUT_TODO_FAILED';

export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_TODO_SUCCESSED = 'DELETE_TODO_SUCCESSED';
export const DELETE_TODO_FAILED = 'DELETE_TODO_FAILED';

export const CHECK_TODO = 'CHECK_TODO';
export const CHECK_TODO_SUCCESSED = 'CHECK_TODO_SUCCESSED';
export const CHECK_TODO_FAILED = 'CHECK_TODO_FAILED';

export const FILTER_TODO = 'FILTER_TODO';
